name: "setup-tfcmt"
description: "Setup suzuki-shunsuke/tfcmt"
author: "shmokmt"
inputs:
  version:
    description: "A version to install tfcmt"
    default: "latest"
runs:
  using: "composite"
  steps:
    - run: sudo bash ${{ github.action_path }}/install.sh -b /usr/local/bin -d ${TFCMT_VERSION}
      shell: bash
      env:
        TFCMT_VERSION: ${{ inputs.version }}
    - run: tfcmt --version
      shell: bash

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'terminal'
  color: 'gray-dark'
