name: "setup-tfcmt"
description: "Setup suzuki-shunsuke/tfcmt"
author: "shmokmt"
inputs:
  version:
    description: "A version to install tfcmt"
    default: "latest"
runs:
  using: "composite"
  steps:
    - run: curl -sfL https://raw.githubusercontent.com/shmokmt/actions-setup-tfcmt/main/install.sh | sudo sh -s  -- -b /usr/local/bin -d
      shell: bash
      env:
        TFCMT_VERSION: ${{ inputs.version }}
    - run: tfcmt --version
      shell: bash

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'terminal'
  color: 'gray-dark'
